config/routes.rb
# Tells Rails how to connect incoming requests to controllers and actions

Rails.application.routes.draw do
  get 'hello_world/index'

  # Resource route (maps HTTP verbs to controller actions automatically):
  resources :events

  root 'hello_world#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  protect_from_forgery with: :null_session, only: Proc.new { |c| c.request.format.json? }

  def index
    @events = Event.all
  end

  def show
    @event = Event.find params[:id]
  end

  def new
    @event = Event.new(event_params)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.save!
    redirect_to @event
  end

  def update
    @events = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
  def event_params
    params.permit(:name, :date, :hour, :description, :local, :repeating_frequency)
  end
end

app/controllers/hello_world_controller.rb
# The controller purpose is to receive spexific requests for the application

class HelloWorldController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.time_select :hour %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_area :local %>
  </div>
  <div class="field">
    <%= f.label :repeating_frequency %><br>
    <%= f.number_field :repeating_frequency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<html>
  <body>
    <h1>Edit Event</h1>

    <form action="/events/:id" method="put">
      Event name:<br>
      <input type="text" name="name" value=""><br>
      Date:<br>
      <input type="text" name="date" value=""><br>
      Hour:<br>
      <input type="text" name="hour" value=""><br>
      Description:<br>
      <input type="text" name="description" value=""><br>
      Local:<br>
      <input type="text" name="local" value=""><br>
      Repeating Frequency:<br>
      <!-- dia todo, algumas horas, pontual -->
      <input type="text" name="repeating_frequency" value=""><br>
      <br>
      <input type="submit" value="Submit">
    </form>

    <%= link_to 'Show', @event %> |
    <%= link_to 'Back', events_path %>
  </body>
</html>

app/views/events/index.erb
<html>
  <body>
    <!-- <p id="notice"><%#= notice %></p> -->
    <h1>Listing Events</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Hour</th>
          <th>Description</th>
          <th>Local</th>
          <th>Repeating frequency</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% if @events %>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.date %></td>
            <td><%= event.hour %></td>
            <td><%= event.description %></td>
            <td><%= event.local %></td>
            <td><%= event.repeating_frequency %></td>
            <td><%= link_to 'Show', event_path(event) %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </table>

    <br>
    <a href="/events/new">New Event</a>
    <!-- <%#= link_to 'New Event', new_event_path %> -->
  </body>
</html>

app/views/events/new.html.erb
<html>
  <body>
    <h1>New Event</h1>
<!-- /hello_world/index.html -->
    <form action="/events/" method="post">
      Event name:<br>
      <input type="text" name="name" value=""><br>
      Date:<br>
      <input type="text" name="date" value=""><br>
      Hour:<br>
      <input type="text" name="hour" value=""><br>
      Description:<br>
      <input type="text" name="description" value=""><br>
      Local:<br>
      <input type="text" name="local" value=""><br>
      Repeating Frequency:<br>
      <!-- dia todo, algumas horas, pontual -->
      <input type="text" name="repeating_frequency" value=""><br>
      <br>
      <input type="submit" value="Submit">
    </form>

  </body>
</html>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @event.hour %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Local:</strong>
  <%= @event.local %>
</p>

<p>
  <strong>Repeating frequency:</strong>
  <%= @event.repeating_frequency %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/hello_world/index.html.erb
<!-- This index is an action from hello_world controller -->
<!-- His purpose is to collect information to provide it to a view -->

<h1>Hello, Rails!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>